In [30]:
%load_ext autoreload
%autoreload 2

import torch
import torch.nn as nn
import torch.nn.functional as F


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [31]:
x1 = torch.tensor([1, 2, 3, 4])
x2 = torch.tensor([5, 6, 7, 8])
x3 = torch.tensor([9, 10, 11 ,12])

a = []
a.append(x1)
a.append(x2)
a.append(x3)

inputs = torch.stack(a)
inputs

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

In [32]:
inputs = inputs.to(torch.float32)
inputs

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])

In [33]:
adaptive_curriculum = nn.Sequential(
                nn.Linear(4, 4),
                nn.ReLU(inplace=True),
                nn.Linear(4, 2))

inequality_param = adaptive_curriculum(inputs)
inequality_param

tensor([[0.3157, 0.1008],
        [0.8093, 0.8172],
        [1.3030, 1.5336]], grad_fn=<AddmmBackward0>)

In [34]:
for name, param in adaptive_curriculum.named_parameters():
    print(name, param.shape)

0.weight torch.Size([4, 4])
0.bias torch.Size([4])
2.weight torch.Size([2, 4])
2.bias torch.Size([2])
