In [12]:
import torch
import math

In [13]:
s=64.0
m=0.50


cos_m = math.cos(m)

print("cos_m == ", cos_m)
print("math.pi == ", math.pi)

sin_m = math.sin(m)
th = math.cos(math.pi - m)
mm = math.sin(math.pi - m) * m


print("th == ", th)
print("mm == ", mm)


#math.cos(math.pi)

cos_m ==  0.8775825618903728
math.pi ==  3.141592653589793
th ==  -0.8775825618903726
mm ==  0.23971276930210156


In [14]:
cos_theta = torch.tensor([[ 0.3931, -0.1480, -0.0346, -0.0787, -0.0883],
        [ 0.2670, -0.1452, -0.0780,  0.0074, -0.1311],
        [ 0.4143, -0.0444, -0.1596, -0.1997, -0.0318],
        [ 0.3799, -0.0584, -0.0891, -0.1351, -0.1052],
        [ 0.3241,  0.0176, -0.1045, -0.0851, -0.1355],
        [-0.0655,  0.2889, -0.1270, -0.0374, -0.1539],
        [-0.1304,  0.3616, -0.1461, -0.0061, -0.0827],
        [-0.0991,  0.3409, -0.1459, -0.1055,  0.0179],
        [-0.0655,  0.2439, -0.0088, -0.0390, -0.1090],
        [-0.0888,  0.3240, -0.1063, -0.0173, -0.0632],
        [-0.1353, -0.0701,  0.2831, -0.0658,  0.0303],
        [-0.0134, -0.0993,  0.3225, -0.0852, -0.0935],
        [-0.1450, -0.0340,  0.3003, -0.0075, -0.0760],
        [-0.0671, -0.1407,  0.3164, -0.0651,  0.0133],
        [-0.0590, -0.0690,  0.2897, -0.1496, -0.0117],
        [-0.0746, -0.0416, -0.0701,  0.3114, -0.1324],
        [-0.0740,  0.0175, -0.1230,  0.4363, -0.1781],
        [-0.0489, -0.0312, -0.0977,  0.3841, -0.1605],
        [-0.0759, -0.0166, -0.1021,  0.3538, -0.1187],
        [-0.1208, -0.0513, -0.0707,  0.3832, -0.1451],
        [-0.1358, -0.0684,  0.0106, -0.0150,  0.1805],
        [-0.1165, -0.1592,  0.0210, -0.0987,  0.3119],
        [-0.1335, -0.0906, -0.0609, -0.1231,  0.3963],
        [-0.1134, -0.0166, -0.0837, -0.2344,  0.4289],
        [-0.0697,  0.0153, -0.0366, -0.2728,  0.3407]])


label = torch.tensor([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4,4])


embbedings_size = 25

origin_cos = cos_theta.clone()

target_logit = cos_theta[torch.arange(0, embbedings_size), label].view(-1, 1)
target_logit

tensor([[0.3931],
        [0.2670],
        [0.4143],
        [0.3799],
        [0.3241],
        [0.2889],
        [0.3616],
        [0.3409],
        [0.2439],
        [0.3240],
        [0.2831],
        [0.3225],
        [0.3003],
        [0.3164],
        [0.2897],
        [0.3114],
        [0.4363],
        [0.3841],
        [0.3538],
        [0.3832],
        [0.1805],
        [0.3119],
        [0.3963],
        [0.4289],
        [0.3407]])

In [15]:
#torch pow는 tensor의 요소끼리 제곱을 한다
sin_theta = torch.sqrt(1.0 - torch.pow(target_logit, 2))
sin_theta

tensor([[0.9195],
        [0.9637],
        [0.9101],
        [0.9250],
        [0.9460],
        [0.9574],
        [0.9323],
        [0.9401],
        [0.9698],
        [0.9461],
        [0.9591],
        [0.9466],
        [0.9538],
        [0.9486],
        [0.9571],
        [0.9503],
        [0.8998],
        [0.9233],
        [0.9353],
        [0.9237],
        [0.9836],
        [0.9501],
        [0.9181],
        [0.9034],
        [0.9402]])

In [16]:
cos_theta_m = target_logit * cos_m - sin_theta * sin_m  # cos(target+margin)
cos_theta_m

tensor([[-0.0959],
        [-0.2277],
        [-0.0728],
        [-0.1101],
        [-0.1691],
        [-0.2054],
        [-0.1297],
        [-0.1515],
        [-0.2509],
        [-0.1692],
        [-0.2114],
        [-0.1708],
        [-0.1938],
        [-0.1771],
        [-0.2046],
        [-0.1823],
        [-0.0485],
        [-0.1056],
        [-0.1379],
        [-0.1065],
        [-0.3131],
        [-0.1818],
        [-0.0924],
        [-0.0567],
        [-0.1518]])

In [17]:
final_target_logit = torch.where(target_logit > th, cos_theta_m, target_logit - mm)
final_target_logit

tensor([[-0.0959],
        [-0.2277],
        [-0.0728],
        [-0.1101],
        [-0.1691],
        [-0.2054],
        [-0.1297],
        [-0.1515],
        [-0.2509],
        [-0.1692],
        [-0.2114],
        [-0.1708],
        [-0.1938],
        [-0.1771],
        [-0.2046],
        [-0.1823],
        [-0.0485],
        [-0.1056],
        [-0.1379],
        [-0.1065],
        [-0.3131],
        [-0.1818],
        [-0.0924],
        [-0.0567],
        [-0.1518]])

In [18]:
cos_theta.scatter_(1, label.view(-1, 1).long(), final_target_logit)

tensor([[-0.0959, -0.1480, -0.0346, -0.0787, -0.0883],
        [-0.2277, -0.1452, -0.0780,  0.0074, -0.1311],
        [-0.0728, -0.0444, -0.1596, -0.1997, -0.0318],
        [-0.1101, -0.0584, -0.0891, -0.1351, -0.1052],
        [-0.1691,  0.0176, -0.1045, -0.0851, -0.1355],
        [-0.0655, -0.2054, -0.1270, -0.0374, -0.1539],
        [-0.1304, -0.1297, -0.1461, -0.0061, -0.0827],
        [-0.0991, -0.1515, -0.1459, -0.1055,  0.0179],
        [-0.0655, -0.2509, -0.0088, -0.0390, -0.1090],
        [-0.0888, -0.1692, -0.1063, -0.0173, -0.0632],
        [-0.1353, -0.0701, -0.2114, -0.0658,  0.0303],
        [-0.0134, -0.0993, -0.1708, -0.0852, -0.0935],
        [-0.1450, -0.0340, -0.1938, -0.0075, -0.0760],
        [-0.0671, -0.1407, -0.1771, -0.0651,  0.0133],
        [-0.0590, -0.0690, -0.2046, -0.1496, -0.0117],
        [-0.0746, -0.0416, -0.0701, -0.1823, -0.1324],
        [-0.0740,  0.0175, -0.1230, -0.0485, -0.1781],
        [-0.0489, -0.0312, -0.0977, -0.1056, -0.1605],
        [-

In [19]:
output = cos_theta * s
output

tensor([[ -6.1345,  -9.4720,  -2.2144,  -5.0368,  -5.6512],
        [-14.5732,  -9.2928,  -4.9920,   0.4736,  -8.3904],
        [ -4.6568,  -2.8416, -10.2144, -12.7808,  -2.0352],
        [ -7.0456,  -3.7376,  -5.7024,  -8.6464,  -6.7328],
        [-10.8239,   1.1264,  -6.6880,  -5.4464,  -8.6720],
        [ -4.1920, -13.1487,  -8.1280,  -2.3936,  -9.8496],
        [ -8.3456,  -8.2976,  -9.3504,  -0.3904,  -5.2928],
        [ -6.3424,  -9.6985,  -9.3376,  -6.7520,   1.1456],
        [ -4.1920, -16.0579,  -0.5632,  -2.4960,  -6.9760],
        [ -5.6832, -10.8305,  -6.8032,  -1.1072,  -4.0448],
        [ -8.6592,  -4.4864, -13.5276,  -4.2112,   1.9392],
        [ -0.8576,  -6.3552, -10.9305,  -5.4528,  -5.9840],
        [ -9.2800,  -2.1760, -12.4006,  -0.4800,  -4.8640],
        [ -4.2944,  -9.0048, -11.3362,  -4.1664,   0.8512],
        [ -3.7760,  -4.4160, -13.0964,  -9.5744,  -0.7488],
        [ -4.7744,  -2.6624,  -4.4864, -11.6678,  -8.4736],
        [ -4.7360,   1.1200,  -7.8720,  

In [20]:
origin_cos * s

tensor([[ 25.1584,  -9.4720,  -2.2144,  -5.0368,  -5.6512],
        [ 17.0880,  -9.2928,  -4.9920,   0.4736,  -8.3904],
        [ 26.5152,  -2.8416, -10.2144, -12.7808,  -2.0352],
        [ 24.3136,  -3.7376,  -5.7024,  -8.6464,  -6.7328],
        [ 20.7424,   1.1264,  -6.6880,  -5.4464,  -8.6720],
        [ -4.1920,  18.4896,  -8.1280,  -2.3936,  -9.8496],
        [ -8.3456,  23.1424,  -9.3504,  -0.3904,  -5.2928],
        [ -6.3424,  21.8176,  -9.3376,  -6.7520,   1.1456],
        [ -4.1920,  15.6096,  -0.5632,  -2.4960,  -6.9760],
        [ -5.6832,  20.7360,  -6.8032,  -1.1072,  -4.0448],
        [ -8.6592,  -4.4864,  18.1184,  -4.2112,   1.9392],
        [ -0.8576,  -6.3552,  20.6400,  -5.4528,  -5.9840],
        [ -9.2800,  -2.1760,  19.2192,  -0.4800,  -4.8640],
        [ -4.2944,  -9.0048,  20.2496,  -4.1664,   0.8512],
        [ -3.7760,  -4.4160,  18.5408,  -9.5744,  -0.7488],
        [ -4.7744,  -2.6624,  -4.4864,  19.9296,  -8.4736],
        [ -4.7360,   1.1200,  -7.8720,  